CREATE TYPE "RecruitmentRequestStatus" AS ENUM ('SUBMITTED','UNDER_REVIEW','APPROVED','REJECTED','CONVERTED','CANCELLED');
CREATE TYPE "InterviewMode" AS ENUM ('IN_PERSON','PHONE','VIDEO');
CREATE TYPE "InterviewStatus" AS ENUM ('SCHEDULED','COMPLETED','NO_SHOW','RESCHEDULED','CANCELLED');
CREATE TYPE "DocumentStatus" AS ENUM ('PENDING','AVAILABLE','QUARANTINED','REJECTED','DELETED');

CREATE TABLE "recruitment_requests" ("id" BIGSERIAL PRIMARY KEY,"public_id" UUID NOT NULL,"tenant_id" BIGINT NOT NULL,"status" "RecruitmentRequestStatus" NOT NULL DEFAULT 'SUBMITTED',"position_title" TEXT NOT NULL,"department" TEXT,"openings" INTEGER NOT NULL DEFAULT 1,"location" TEXT NOT NULL,"details" JSONB NOT NULL,"vacancy_id" BIGINT,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL);
CREATE UNIQUE INDEX "recruitment_requests_public_id_key" ON "recruitment_requests"("public_id");CREATE UNIQUE INDEX "recruitment_requests_vacancy_id_key" ON "recruitment_requests"("vacancy_id");CREATE INDEX "recruitment_requests_tenant_id_status_created_at_idx" ON "recruitment_requests"("tenant_id","status","created_at");
ALTER TABLE "recruitment_requests" ADD CONSTRAINT "recruitment_requests_tenant_id_fkey" FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT;ALTER TABLE "recruitment_requests" ADD CONSTRAINT "recruitment_requests_vacancy_id_fkey" FOREIGN KEY("vacancy_id") REFERENCES "vacancies"("id") ON DELETE RESTRICT;

CREATE TABLE "vacancy_assignments" ("vacancy_id" BIGINT NOT NULL,"user_id" BIGINT NOT NULL,"assigned_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY("vacancy_id","user_id"));CREATE INDEX "vacancy_assignments_user_id_idx" ON "vacancy_assignments"("user_id");ALTER TABLE "vacancy_assignments" ADD CONSTRAINT "vacancy_assignments_vacancy_id_fkey" FOREIGN KEY("vacancy_id") REFERENCES "vacancies"("id") ON DELETE CASCADE;ALTER TABLE "vacancy_assignments" ADD CONSTRAINT "vacancy_assignments_user_id_fkey" FOREIGN KEY("user_id") REFERENCES "users"("id") ON DELETE RESTRICT;

CREATE TABLE "vacancy_status_history" ("id" BIGSERIAL PRIMARY KEY,"vacancy_id" BIGINT NOT NULL,"from_status" "VacancyStatus","to_status" "VacancyStatus" NOT NULL,"changed_by_id" BIGINT NOT NULL,"reason" TEXT,"changed_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE INDEX "vacancy_status_history_vacancy_id_changed_at_idx" ON "vacancy_status_history"("vacancy_id","changed_at");ALTER TABLE "vacancy_status_history" ADD CONSTRAINT "vacancy_status_history_vacancy_id_fkey" FOREIGN KEY("vacancy_id") REFERENCES "vacancies"("id") ON DELETE CASCADE;

CREATE TABLE "candidate_experiences" ("id" BIGSERIAL PRIMARY KEY,"candidate_id" BIGINT NOT NULL,"company" TEXT NOT NULL,"position" TEXT NOT NULL,"started_on" DATE NOT NULL,"ended_on" DATE,"description" TEXT);CREATE INDEX "candidate_experiences_candidate_id_idx" ON "candidate_experiences"("candidate_id");ALTER TABLE "candidate_experiences" ADD CONSTRAINT "candidate_experiences_candidate_id_fkey" FOREIGN KEY("candidate_id") REFERENCES "candidates"("id") ON DELETE CASCADE;
CREATE TABLE "candidate_educations" ("id" BIGSERIAL PRIMARY KEY,"candidate_id" BIGINT NOT NULL,"institution" TEXT NOT NULL,"degree" TEXT NOT NULL,"field" TEXT,"completed_on" DATE);CREATE INDEX "candidate_educations_candidate_id_idx" ON "candidate_educations"("candidate_id");ALTER TABLE "candidate_educations" ADD CONSTRAINT "candidate_educations_candidate_id_fkey" FOREIGN KEY("candidate_id") REFERENCES "candidates"("id") ON DELETE CASCADE;

CREATE TABLE "interviews" ("id" BIGSERIAL PRIMARY KEY,"public_id" UUID NOT NULL,"application_id" BIGINT NOT NULL,"interviewer_user_id" BIGINT NOT NULL,"mode" "InterviewMode" NOT NULL,"status" "InterviewStatus" NOT NULL DEFAULT 'SCHEDULED',"scheduled_at" TIMESTAMPTZ(6) NOT NULL,"duration_minutes" INTEGER NOT NULL,"location" TEXT,"meeting_url" TEXT,"score" DECIMAL(5,2),"notes" TEXT,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updated_at" TIMESTAMPTZ(6) NOT NULL);CREATE UNIQUE INDEX "interviews_public_id_key" ON "interviews"("public_id");CREATE INDEX "interviews_application_id_scheduled_at_idx" ON "interviews"("application_id","scheduled_at");CREATE INDEX "interviews_interviewer_user_id_scheduled_at_idx" ON "interviews"("interviewer_user_id","scheduled_at");ALTER TABLE "interviews" ADD CONSTRAINT "interviews_application_id_fkey" FOREIGN KEY("application_id") REFERENCES "applications"("id") ON DELETE CASCADE;ALTER TABLE "interviews" ADD CONSTRAINT "interviews_interviewer_user_id_fkey" FOREIGN KEY("interviewer_user_id") REFERENCES "users"("id") ON DELETE RESTRICT;

CREATE TABLE "documents" ("id" BIGSERIAL PRIMARY KEY,"public_id" UUID NOT NULL,"tenant_id" BIGINT NOT NULL,"owner_type" TEXT NOT NULL,"owner_public_id" UUID NOT NULL,"storage_key" TEXT NOT NULL,"original_name" TEXT NOT NULL,"mime_type" TEXT NOT NULL,"size_bytes" BIGINT NOT NULL,"checksum" TEXT,"status" "DocumentStatus" NOT NULL DEFAULT 'PENDING',"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,"deleted_at" TIMESTAMPTZ(6));CREATE UNIQUE INDEX "documents_public_id_key" ON "documents"("public_id");CREATE UNIQUE INDEX "documents_storage_key_key" ON "documents"("storage_key");CREATE INDEX "documents_tenant_id_owner_type_owner_public_id_idx" ON "documents"("tenant_id","owner_type","owner_public_id");ALTER TABLE "documents" ADD CONSTRAINT "documents_tenant_id_fkey" FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT;
