CREATE TABLE "candidate_certifications" ("id" BIGSERIAL PRIMARY KEY,"candidate_id" BIGINT NOT NULL,"name" TEXT NOT NULL,"issuer" TEXT,"issued_on" DATE,"expires_on" DATE,CONSTRAINT "candidate_certifications_candidate_id_fkey" FOREIGN KEY("candidate_id") REFERENCES "candidates"("id") ON DELETE CASCADE);CREATE INDEX "candidate_certifications_candidate_id_idx" ON "candidate_certifications"("candidate_id");
CREATE TABLE "candidate_languages" ("id" BIGSERIAL PRIMARY KEY,"candidate_id" BIGINT NOT NULL,"language" TEXT NOT NULL,"proficiency" TEXT NOT NULL,CONSTRAINT "candidate_languages_candidate_id_fkey" FOREIGN KEY("candidate_id") REFERENCES "candidates"("id") ON DELETE CASCADE);CREATE UNIQUE INDEX "candidate_languages_candidate_id_language_key" ON "candidate_languages"("candidate_id","language");
CREATE TABLE "candidate_competencies" ("id" BIGSERIAL PRIMARY KEY,"candidate_id" BIGINT NOT NULL,"name" TEXT NOT NULL,"level" TEXT,CONSTRAINT "candidate_competencies_candidate_id_fkey" FOREIGN KEY("candidate_id") REFERENCES "candidates"("id") ON DELETE CASCADE);CREATE UNIQUE INDEX "candidate_competencies_candidate_id_name_key" ON "candidate_competencies"("candidate_id","name");
CREATE TABLE "candidate_references" ("id" BIGSERIAL PRIMARY KEY,"candidate_id" BIGINT NOT NULL,"name" TEXT NOT NULL,"relationship" TEXT NOT NULL,"company" TEXT,"phone" TEXT,"email" TEXT,CONSTRAINT "candidate_references_candidate_id_fkey" FOREIGN KEY("candidate_id") REFERENCES "candidates"("id") ON DELETE CASCADE);CREATE INDEX "candidate_references_candidate_id_idx" ON "candidate_references"("candidate_id");
CREATE TABLE "candidate_consents" ("id" BIGSERIAL PRIMARY KEY,"candidate_id" BIGINT NOT NULL,"purpose" TEXT NOT NULL,"notice_version" TEXT NOT NULL,"accepted" BOOLEAN NOT NULL,"accepted_at" TIMESTAMPTZ(6) NOT NULL,"medium" TEXT NOT NULL,"revoked_at" TIMESTAMPTZ(6),CONSTRAINT "candidate_consents_candidate_id_fkey" FOREIGN KEY("candidate_id") REFERENCES "candidates"("id") ON DELETE CASCADE);CREATE INDEX "candidate_consents_candidate_id_purpose_accepted_at_idx" ON "candidate_consents"("candidate_id","purpose","accepted_at");
CREATE TABLE "candidate_tags" ("id" BIGSERIAL PRIMARY KEY,"tenant_id" BIGINT NOT NULL,"name" TEXT NOT NULL,"color" TEXT,CONSTRAINT "candidate_tags_tenant_id_fkey" FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE);CREATE UNIQUE INDEX "candidate_tags_tenant_id_name_key" ON "candidate_tags"("tenant_id","name");
CREATE TABLE "candidate_tag_assignments" ("candidate_id" BIGINT NOT NULL,"tag_id" BIGINT NOT NULL,PRIMARY KEY("candidate_id","tag_id"),CONSTRAINT "candidate_tag_assignments_candidate_id_fkey" FOREIGN KEY("candidate_id") REFERENCES "candidates"("id") ON DELETE CASCADE,CONSTRAINT "candidate_tag_assignments_tag_id_fkey" FOREIGN KEY("tag_id") REFERENCES "candidate_tags"("id") ON DELETE CASCADE);
CREATE TABLE "interview_form_versions" ("id" BIGSERIAL PRIMARY KEY,"public_id" UUID NOT NULL,"tenant_id" BIGINT NOT NULL,"name" TEXT NOT NULL,"version" INTEGER NOT NULL,"definition" JSONB NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "interview_form_versions_tenant_id_fkey" FOREIGN KEY("tenant_id") REFERENCES "tenants"("id") ON DELETE RESTRICT);CREATE UNIQUE INDEX "interview_form_versions_public_id_key" ON "interview_form_versions"("public_id");CREATE UNIQUE INDEX "interview_form_versions_tenant_id_name_version_key" ON "interview_form_versions"("tenant_id","name","version");CREATE INDEX "interview_form_versions_tenant_id_active_idx" ON "interview_form_versions"("tenant_id","active");
ALTER TABLE "interviews" ADD COLUMN "form_version_id" BIGINT,ADD COLUMN "responses" JSONB;ALTER TABLE "interviews" ADD CONSTRAINT "interviews_form_version_id_fkey" FOREIGN KEY("form_version_id") REFERENCES "interview_form_versions"("id") ON DELETE RESTRICT;
