import { notFound, redirect } from "next/navigation";
import { getCurrentSession } from "@/modules/identity/infrastructure/current-session";
import { prisma } from "@/shared/infrastructure/database/prisma";
import { ClientDecisionActions } from "@/components/client-decision-actions";

export default async function Page({ params }: { params: Promise<{ publicId: string }> }) {
  const session = await getCurrentSession(); if (!session) redirect("/iniciar-sesion"); const { publicId } = await params;
  const shortlist = await prisma.shortlist.findFirst({ where: { publicId, status: "PUBLISHED", vacancy: { clientTenantId: session.tenantId } }, select: { vacancy: { select: { publicId: true, title: true } }, entries: { orderBy: { position: "asc" }, select: { position: true, inclusionReason: true, application: { select: { publicId: true, status: true, candidate: { select: { firstName: true, lastName: true, educations: { take: 2 }, competencies: { take: 8 }, experiences: { orderBy: { startedOn: "desc" }, take: 3 } } }, scoreRuns: { orderBy: { calculatedAt: "desc" }, take: 1, select: { total: true } } } } } } } });
  if (!shortlist) notFound();
  return <main className="portal-detail"><a href={`/portal/procesos/${shortlist.vacancy.publicId}`}>← Volver al proceso</a><header><span className="eyebrow">Comparación de terna</span><h1>{shortlist.vacancy.title}</h1><p>La puntuación facilita la comparación; la decisión final requiere criterio humano.</p></header><div className="comparison-grid">{shortlist.entries.map(({ application, position, inclusionReason }) => <article key={application.publicId}><span className="rank">#{position}</span><h2>{application.candidate.firstName} {application.candidate.lastName}</h2><strong>{application.scoreRuns[0] ? `${Number(application.scoreRuns[0].total).toFixed(1)} / 100` : "Sin puntuación"}</strong><h3>Experiencia reciente</h3>{application.candidate.experiences.map((experience) => <p key={`${experience.company}-${experience.position}`}><b>{experience.position}</b><br />{experience.company}</p>)}<h3>Formación</h3>{application.candidate.educations.map((education) => <p key={`${education.institution}-${education.degree}`}>{education.degree}<br /><small>{education.institution}</small></p>)}<h3>Competencias</h3><div className="chips">{application.candidate.competencies.map((competency) => <span key={competency.name}>{competency.name}</span>)}</div><h3>Motivo de inclusión</h3><p>{inclusionReason}</p><ClientDecisionActions applicationPublicId={application.publicId} /></article>)}</div><a className="button report-button" href={`/api/client/shortlists/${publicId}/report`}>Descargar informe ejecutivo</a></main>;
}
